stages:
  - build
  - test

variables:
  BUILD_DIR: build
  GIT_SUBMODULE_STRATEGY: recursive

# Build stage components

.macos_runner: &macos_runner
  tags:
    - macos
    - m1

.linux_runner: &linux_runner
  tags:
    - nvidia-docker

.windows_runner: &windows_runner
  tags:
    - win10-gpu

.linux_dependencies: &linux_dependencies
  before_script:
    - echo Dorado dependency stage
    - apt-get update && apt-get install -y --no-install-recommends libhdf5-dev

.build_dorado: &build_dorado
  stage: build
  script:
    - echo Dorado build stage
    - cmake ${BUILD_OPTIONS} -S . -B ${BUILD_DIR}
    - cmake --build ${BUILD_DIR} --config Release ${BUILD_THREADS}
    - ctest -C Release --test-dir ${BUILD_DIR}
  # We probably want to limit the amount of stuff in the artifacts by selecting out just the built EXEs
  artifacts:
    paths:
      - build
    expire_in: 1 day

# Build stages

build:linux:x86:focal:install_deps:
  image: ${DORADO_NO_DEPS}
  variables:
    BUILD_THREADS: "-- -j 8"
  <<: *linux_dependencies
  <<: *linux_runner
  <<: *build_dorado
  when: manual

build:linux:x86:focal:
  image: ${DORADO_DEPS}
  variables:
    BUILD_OPTIONS: "-DDORADO_LIBTORCH_DIR=/usr/local/libtorch"
    BUILD_THREADS: "-- -j 8"
  <<: *linux_runner
  <<: *build_dorado
  
build:windows:
  variables:
    BUILD_OPTIONS: "-A x64"
  <<: *windows_runner
  <<: *build_dorado
  when: manual

build:macos:m1:
  variables:
    BUILD_THREADS: "-- -j 8"
  <<: *macos_runner
  <<: *build_dorado
  
# Test stage components

.test_dorado: &test_dorado
  stage: test
  script:
    - echo Dorado app test stage
    - curl -sSL https://nanoporetech.box.com/shared/static/g6rbgd12xfunw5plgec3zlyy35692vy3.zip -o model.zip
    - unzip model.zip
    - ./${BUILD_DIR}/bin/dorado basecall dna_r9.4.1_e8_hac@v3.3 ./unit_test/data/ -r 1 -b 384 > calls.fastq

# Test stages

test:linux:x86:focal:
  image: ${DORADO_DEPS}
  <<: *linux_runner
  <<: *test_dorado
  needs:
    - build:linux:x86:focal

test:macos:m1:
  <<: *macos_runner
  <<: *test_dorado
  needs:
    - build:macos:m1
  # tmp - remove after archive builds sorted
  before_script:
    - mkdir -p dorado/3rdparty/torch-1.10.2-Darwin/
    - curl -sL "https://files.pythonhosted.org/packages/7b/91/89bbe2316b93671b6bccec094df6bc66109cf6d21a364cd2f1becd11ba3c/torch-1.10.2-cp39-none-macosx_11_0_arm64.whl" --output dorado/3rdparty/torch-1.10.2-Darwin/torch.whl
    - unzip -q dorado/3rdparty/torch-1.10.2-Darwin/torch.whl -d dorado/3rdparty/torch-1.10.2-Darwin
