name: build-dorado

on: [push]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2016, macos-12]
        include:
          - os: windows-2016
            arch: "-A x64"
          - os: macos-12
            args: "-D OPENSSL_ROOT_DIR=/usr/local/opt/openssl@3 -D CMAKE_OSX_ARCHITECTURES=arm64"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1
    - name: Set up cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.21.x'
    - name: Install Cuda
      uses: Jimver/cuda-toolkit@v0.2.7
      if: matrix.os != 'macos-12'
      id: cuda-toolkit
      with:
        cuda: '11.3.0'
    - name: Install dependencies from brew
      if: matrix.os == 'macos-12'
      run: brew install openssl hdf5
    - name: Install dependencies from apt
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libhdf5-dev libssl-dev libzstd-dev
    - name: Set up Windows path
      uses: myci-actions/export-env-var-powershell@1
      if: matrix.os == 'windows-2016'
      with:
        name: PATH
        value: d:\a\dorado\dorado\bin;$env:PATH
    - name: Build dorado
      run: |
        cmake -S . -B cmake-build ${{ matrix.arch }} ${{ matrix.args }}
        cmake --build cmake-build --config Release --target install -j 4
        ctest -C Release --test-dir cmake-build
