name: build-dorado

on: [push]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2016]
        include:
          - os: windows-2016
            arch: "-A x64"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.21.x'
    - uses: Jimver/cuda-toolkit@v0.2.7
      id: cuda-toolkit
      with:
        cuda: '11.3.0'
    - name: Install dependencies from apt
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libhdf5-dev libssl-dev libzstd-dev
    - name: Set up Windows path
      if: matrix.os == 'windows-2016'
      run: export PATH=${PATH}:${PWD}/dorado/3rdparty/torch-1.10.2-Windows/libtorch/lib:${PWD}/dorado/3rdparty/cmake-build-zstd/lib/Release:${PWD}/dorado/3rdparty/zlib-1.2.12/install/bin:${PWD}/dorado/3rdparty/pod5-0.0.14-Windows/lib
    - name: Build dorado
      run: |
        cmake -S . -B cmake-build ${{ matrix.arch }}
        cmake --build cmake-build --config Release --target install -j 4
        ctest -C Release --test-dir cmake-build
