name: build-dorado

on: [push, pull_request]

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019]
        include:
          - os: windows-2019
            arch: "-A x64"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Clean up diskspace
      if: matrix.os == 'ubuntu-20.04'
      run: sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/share/boost "$AGENT_TOOLSDIRECTORY"
    - name: Set up cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.21.x'
    - uses: Jimver/cuda-toolkit@v0.2.10
      id: cuda-toolkit
      with:
        cuda: '11.8.0'
    - name: Install dependencies from apt
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libhdf5-dev libssl-dev libzstd-dev autoconf
    - name: Build dorado
      run: |
        cmake -S . -B cmake-build ${{ matrix.arch }}
        cmake --build cmake-build --config Release -j 4
        ctest -C Release --test-dir cmake-build --output-on-failure
